#homework_week_2: homework_week_2.o
# 	gcc homework_week_2.o -o homework_week_2
# 
#homework_week_2.o: homework_week_2.c
# 	gcc -c homework_week_2.c
# 
week3.exe: week3.o
	gcc week3.o -o week3.exe

week3.o: week3.c
	gcc -c week3.c

sortedlists.exe: sortedlists.o
	gcc sortedlists.o -o sortedlists.exe

sortedlists.o: sortedlists.c
	gcc -c sortedlists.c

#binary_tree: binary_tree.o
#	gcc binary_tree.o -o binary_tree
#
#binary_tree.o: binary_tree.c
#	gcc -c binary_tree.c
#
clean:
	rm *.o
	rm *.exe
